module.exports = {
  login_error: 'error_message_invalid_password_or_number',
  digit_code_check: 'ok',
  digit_code_send_err: 'error_message_can\'t_send_code',
  verified_error: 'error_message_already_verified',
  digit_code_error: 'error_message_invalid_code',
  login: 'ok',
  not_authenticate: 'User not authenticated',
  not_found: 'Not found',
  nothing_updated: 'nothing_updated',
  phone_err: {phoneNumber: "error_message_phone_number_already_busy"},
  user_create: "user_created",
  driver_create: "driver_created",
  driver_exist: "error_message_driver_already_busy",
  email_err: "error_message_email_already_busy",
  number_exist: "error_message_number_already_busy",
  perm_err: 'Permission denied',
  user_update: 'user_updated',
  driver_update: 'driver_updated',
  user_delete: 'user_deleted',
  driver_delete: 'driver_deleted',
  not_auth: 'You aren\'t authorized',
  forbidden: 'error_message_not_permission_update_country',
  location_create: 'country_created',
  country_exist: 'error_message_country_already_exist',
  city_exist: 'error_message_city_already_exist',
  location_update: 'country_updated',
  location_delete: 'country_deleted',
  country_del_err: 'This country has cities',
  city_create: 'city_created',
  city_update: 'city_updated',
  city_delete: 'city_deleted',
  city_has_route: 'This city has route',
  route_create: 'route_created',
  route_delete: 'route_deleted',
  route_has_service: 'This route has service',
  partner_create: 'partner_created',
  partner_delete: 'partner_deleted',
  partner_update: 'partner_updated',
  service_create: 'service_created',
  service_update: 'service_updated',
  service_delete: 'service_deleted',
  service_has_ticket: 'This service has ticket',
  ticket_create: 'ticket_created',
  ticket_update: 'ticket_updated',
  ticket_delete: 'ticket_deleted',
  available_count_error: 'available_count_error',
  ref_error: 'This referral already exist',
  user_exist_err: 'No such user',
  city_exist_err: 'No such city',
  driver_exist_err: 'No such driver',
  route_exist_err: 'No such route',
  service_exist_err: 'No such service',
  invitor_exist_err: {invitor: 'No such user'},
};
